echo "adfasdf";
echo "Nigga";
echo "fuck";
echo "asslicker";
echo "pussyassnigga";
echo "dickhead";
echo "pre, nagdagdag ako.";
echo "pre, nagdagdag din ako.";
echo "footer: mobile view done";
echo "sinira ko na yung header";
echo "dilawsaitlog";
echo "adfasdf";
echo "github > phub";
echo "wgaga";
echo "test lang to";
echo "latest ver of geol";
echo "nig";
echo "agawgwagwagagwa";